// MotionCraft/src/components/timeline/Timeline.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useLayerStore } from '@/stores/useLayerStore'
import { useTimelineStore } from '@/stores/useTimelineStore'
import TrackList from './TrackList.vue'
import TimelineRuler from './TimelineRuler.vue'

const layerStore = useLayerStore()
const timelineStore = useTimelineStore()

const timelineContainerRef = ref<HTMLElement | null>(null)
const isDraggingPlayhead = ref(false)

/**
 * 时间轴总宽度（像素）
 */
const timelineWidth = computed(() => {
  return (timelineStore.timeline.duration / 1000) * timelineStore.timeline.zoom
})

/**
 * 播放头位置（像素）
 */
const playheadPosition = computed(() => {
  return (timelineStore.timeline.currentTime / 1000) * timelineStore.timeline.zoom
})

/**
 * 开始拖拽播放头
 */
const startDragPlayhead = (e: MouseEvent) => {
  isDraggingPlayhead.value = true
  document.addEventListener('mousemove', onDragPlayhead)
  document.addEventListener('mouseup', stopDragPlayhead)
}

/**
 * 拖拽播放头
 */
const onDragPlayhead = (e: MouseEvent) => {
  if (!isDraggingPlayhead.value || !timelineContainerRef.value) return
  
  const rect = timelineContainerRef.value.getBoundingClientRect()
  const scrollLeft = timelineContainerRef.value.scrollLeft
  const x = e.clientX - rect.left + scrollLeft - 200 // 减去轨道头部宽度
  
  const timeMs = (x / timelineStore.timeline.zoom) * 1000
  timelineStore.setCurrentTime(Math.max(0, Math.min(timeMs, timelineStore.timeline.duration)))
}

/**
 * 停止拖拽播放头
 */
const stopDragPlayhead = () => {
  isDraggingPlayhead.value = false
  document.removeEventListener('mousemove', onDragPlayhead)
  document.removeEventListener('mouseup', stopDragPlayhead)
}

/**
 * 滚轮缩放时间轴
 */
const handleWheel = (e: WheelEvent) => {
  if (e.ctrlKey) {
    e.preventDefault()
    const delta = e.deltaY > 0 ? 0.9 : 1.1
    timelineStore.setZoom(timelineStore.timeline.zoom * delta)
  }
}
</script>

<template>
  <div 
    ref="timelineContainerRef"
    class="w-full h-full overflow-auto relative"
    @wheel="handleWheel"
  >
    <div 
      class="relative min-h-full"
      :style="{ width: `${timelineWidth + 200}px` }"
    >
      <!-- 时间标尺 -->
      <TimelineRuler 
        class="sticky top-0 z-20"
        :width="timelineWidth"
      />
      
      <!-- 轨道列表 -->
      <TrackList class="mt-[30px]" />
      
      <!-- 播放头 -->
      <div 
        class="playhead"
        :style="{ left: `${playheadPosition + 200}px` }"
        @mousedown="startDragPlayhead"
      >
        <div class="playhead-head" />
      </div>
    </div>
    
    <!-- 空状态提示 -->
    <div 
      v-if="layerStore.layers.length === 0"
      class="absolute inset-0 flex items-center justify-center pointer-events-none"
    >
      <div class="text-center text-[var(--text-secondary)] text-sm">
        <div>暂无轨道</div>
        <div class="text-xs mt-1">添加图层后自动创建轨道</div>
      </div>
    </div>
  </div>
</template>

<style scoped>
/* 时间轴主容器样式 */
</style>

// motioncraft-web/src/react/components/timeline/Timeline.tsx
// 文件路径: src/react/components/timeline/Timeline.tsx

/**
 * 时间轴主组件
 */

import React, { useRef, useEffect } from 'react';
import TrackList from './TrackList';
import TimelineRuler from './TimelineRuler';
import Playhead from './Playhead';
import { useTimelineStore } from '@react/stores/useTimelineStore';
import { useLayerStore } from '@react/stores/useLayerStore';

export const Timeline: React.FC = () => {
  const containerRef = useRef<HTMLDivElement>(null);
  const zoom = useTimelineStore(state => state.zoom);
  const scrollX = useTimelineStore(state => state.scrollX);
  const duration = useTimelineStore(state => state.duration);
  const currentTime = useTimelineStore(state => state.currentTime);
  const isPlaying = useTimelineStore(state => state.isPlaying);
  const setScrollX = useTimelineStore(state => state.setScrollX);
  const setCurrentTime = useTimelineStore(state => state.setCurrentTime);
  const setZoom = useTimelineStore(state => state.setZoom);
  
  const layers = useLayerStore(state => state.layers);
  const syncTracksFromLayers = useTimelineStore(state => state.syncTracksFromLayers);

  // 同步轨道和图层
  useEffect(() => {
    syncTracksFromLayers(layers);
  }, [layers, syncTracksFromLayers]);

  // 播放时滚动
  useEffect(() => {
    if (!isPlaying || !containerRef.current) return;

    const pixelsPerMs = zoom / 1000;
    const currentPixel = currentTime * pixelsPerMs;
    const container = containerRef.current;
    const viewportWidth = container.clientWidth;

    if (currentPixel > scrollX + viewportWidth - 100) {
      setScrollX(currentPixel - viewportWidth + 100);
    } else if (currentPixel < scrollX) {
      setScrollX(Math.max(0, currentPixel - 100));
    }
  }, [currentTime, isPlaying, zoom, scrollX, setScrollX]);

  // 滚轮缩放
  const handleWheel = (e: React.WheelEvent) => {
    if (e.ctrlKey) {
      e.preventDefault();
      const delta = e.deltaY > 0 ? -10 : 10;
      setZoom(zoom + delta);
    } else if (e.shiftKey) {
      e.preventDefault();
      setScrollX(scrollX + e.deltaY);
    } else {
      setScrollX(scrollX + e.deltaX);
    }
  };

  // 点击时间轴跳转
  const handleClick = (e: React.MouseEvent) => {
    if (!containerRef.current) return;

    const rect = containerRef.current.getBoundingClientRect();
    const x = e.clientX - rect.left - 150 + scrollX; // 减去轨道列表宽度
    const pixelsPerMs = zoom / 1000;
    const time = x / pixelsPerMs;
    
    setCurrentTime(Math.max(0, Math.min(time, duration)));
  };

  return (
    <div
      ref={containerRef}
      className="w-full h-full overflow-hidden relative bg-[var(--mc-track-bg)]"
      onWheel={handleWheel}
      onClick={handleClick}
    >
      {/* 时间标尺 */}
      <div className="absolute top-0 left-[150px] right-0 h-8 border-b border-[var(--mc-border)] z-10">
        <TimelineRuler />
      </div>

      {/* 播放头 */}
      <Playhead />

      {/* 轨道列表区域 */}
      <div className="flex h-full pt-8">
        {/* 左侧轨道名称 */}
        <div className="w-[150px] flex-shrink-0 bg-[var(--mc-bg-secondary)] border-r border-[var(--mc-border)] overflow-y-hidden">
          <TrackList showClips={false} />
        </div>

        {/* 右侧时间轴内容 */}
        <div
          className="flex-1 overflow-x-hidden relative"
          style={{ transform: `translateX(-${scrollX}px)` }}
        >
          <div style={{ width: (duration / 1000) * zoom }}>
            <TrackList showClips={true} />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Timeline;
